mongodb:
  host: entertainme.qe4nfvv.mongodb.net
  username: entertainment
  password: Ss3r8LiphvmoXayF
  database: EntertainMe
  
  
api:
  security:
    token:
      secret: "${JWT_SECRET:my-secret-key}"